// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPublicGetHistoricalVolatilityParams creates a new GetPublicGetHistoricalVolatilityParams object
// with the default values initialized.
func NewGetPublicGetHistoricalVolatilityParams() *GetPublicGetHistoricalVolatilityParams {
	var ()
	return &GetPublicGetHistoricalVolatilityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPublicGetHistoricalVolatilityParamsWithTimeout creates a new GetPublicGetHistoricalVolatilityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPublicGetHistoricalVolatilityParamsWithTimeout(timeout time.Duration) *GetPublicGetHistoricalVolatilityParams {
	var ()
	return &GetPublicGetHistoricalVolatilityParams{

		timeout: timeout,
	}
}

// NewGetPublicGetHistoricalVolatilityParamsWithContext creates a new GetPublicGetHistoricalVolatilityParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPublicGetHistoricalVolatilityParamsWithContext(ctx context.Context) *GetPublicGetHistoricalVolatilityParams {
	var ()
	return &GetPublicGetHistoricalVolatilityParams{

		Context: ctx,
	}
}

// NewGetPublicGetHistoricalVolatilityParamsWithHTTPClient creates a new GetPublicGetHistoricalVolatilityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPublicGetHistoricalVolatilityParamsWithHTTPClient(client *http.Client) *GetPublicGetHistoricalVolatilityParams {
	var ()
	return &GetPublicGetHistoricalVolatilityParams{
		HTTPClient: client,
	}
}

/*GetPublicGetHistoricalVolatilityParams contains all the parameters to send to the API endpoint
for the get public get historical volatility operation typically these are written to a http.Request
*/
type GetPublicGetHistoricalVolatilityParams struct {

	/*Currency
	  The currency symbol

	*/
	Currency string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get public get historical volatility params
func (o *GetPublicGetHistoricalVolatilityParams) WithTimeout(timeout time.Duration) *GetPublicGetHistoricalVolatilityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get public get historical volatility params
func (o *GetPublicGetHistoricalVolatilityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get public get historical volatility params
func (o *GetPublicGetHistoricalVolatilityParams) WithContext(ctx context.Context) *GetPublicGetHistoricalVolatilityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get public get historical volatility params
func (o *GetPublicGetHistoricalVolatilityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get public get historical volatility params
func (o *GetPublicGetHistoricalVolatilityParams) WithHTTPClient(client *http.Client) *GetPublicGetHistoricalVolatilityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get public get historical volatility params
func (o *GetPublicGetHistoricalVolatilityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCurrency adds the currency to the get public get historical volatility params
func (o *GetPublicGetHistoricalVolatilityParams) WithCurrency(currency string) *GetPublicGetHistoricalVolatilityParams {
	o.SetCurrency(currency)
	return o
}

// SetCurrency adds the currency to the get public get historical volatility params
func (o *GetPublicGetHistoricalVolatilityParams) SetCurrency(currency string) {
	o.Currency = currency
}

// WriteToRequest writes these params to a swagger request
func (o *GetPublicGetHistoricalVolatilityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param currency
	qrCurrency := o.Currency
	qCurrency := qrCurrency
	if qCurrency != "" {
		if err := r.SetQueryParam("currency", qCurrency); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
