// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/adampointer/go-deribit/v3/models"
)

// GetPublicGetCurrenciesReader is a Reader for the GetPublicGetCurrencies structure.
type GetPublicGetCurrenciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPublicGetCurrenciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPublicGetCurrenciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPublicGetCurrenciesOK creates a GetPublicGetCurrenciesOK with default headers values
func NewGetPublicGetCurrenciesOK() *GetPublicGetCurrenciesOK {
	return &GetPublicGetCurrenciesOK{}
}

/*GetPublicGetCurrenciesOK handles this case with default header values.

ok response
*/
type GetPublicGetCurrenciesOK struct {
	Payload *models.PublicGetCurrenciesResponse
}

func (o *GetPublicGetCurrenciesOK) Error() string {
	return fmt.Sprintf("[GET /public/get_currencies][%d] getPublicGetCurrenciesOK  %+v", 200, o.Payload)
}

func (o *GetPublicGetCurrenciesOK) GetPayload() *models.PublicGetCurrenciesResponse {
	return o.Payload
}

func (o *GetPublicGetCurrenciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PublicGetCurrenciesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
