// Code generated by go-swagger; DO NOT EDIT.

package trading

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrivateCancelAllParams creates a new GetPrivateCancelAllParams object
// with the default values initialized.
func NewGetPrivateCancelAllParams() *GetPrivateCancelAllParams {

	return &GetPrivateCancelAllParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrivateCancelAllParamsWithTimeout creates a new GetPrivateCancelAllParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrivateCancelAllParamsWithTimeout(timeout time.Duration) *GetPrivateCancelAllParams {

	return &GetPrivateCancelAllParams{

		timeout: timeout,
	}
}

// NewGetPrivateCancelAllParamsWithContext creates a new GetPrivateCancelAllParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrivateCancelAllParamsWithContext(ctx context.Context) *GetPrivateCancelAllParams {

	return &GetPrivateCancelAllParams{

		Context: ctx,
	}
}

// NewGetPrivateCancelAllParamsWithHTTPClient creates a new GetPrivateCancelAllParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrivateCancelAllParamsWithHTTPClient(client *http.Client) *GetPrivateCancelAllParams {

	return &GetPrivateCancelAllParams{
		HTTPClient: client,
	}
}

/*GetPrivateCancelAllParams contains all the parameters to send to the API endpoint
for the get private cancel all operation typically these are written to a http.Request
*/
type GetPrivateCancelAllParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get private cancel all params
func (o *GetPrivateCancelAllParams) WithTimeout(timeout time.Duration) *GetPrivateCancelAllParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get private cancel all params
func (o *GetPrivateCancelAllParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get private cancel all params
func (o *GetPrivateCancelAllParams) WithContext(ctx context.Context) *GetPrivateCancelAllParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get private cancel all params
func (o *GetPrivateCancelAllParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get private cancel all params
func (o *GetPrivateCancelAllParams) WithHTTPClient(client *http.Client) *GetPrivateCancelAllParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get private cancel all params
func (o *GetPrivateCancelAllParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrivateCancelAllParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
