// Code generated by go-swagger; DO NOT EDIT.

package private

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrivateChangeSubaccountNameParams creates a new GetPrivateChangeSubaccountNameParams object
// with the default values initialized.
func NewGetPrivateChangeSubaccountNameParams() *GetPrivateChangeSubaccountNameParams {
	var ()
	return &GetPrivateChangeSubaccountNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrivateChangeSubaccountNameParamsWithTimeout creates a new GetPrivateChangeSubaccountNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrivateChangeSubaccountNameParamsWithTimeout(timeout time.Duration) *GetPrivateChangeSubaccountNameParams {
	var ()
	return &GetPrivateChangeSubaccountNameParams{

		timeout: timeout,
	}
}

// NewGetPrivateChangeSubaccountNameParamsWithContext creates a new GetPrivateChangeSubaccountNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrivateChangeSubaccountNameParamsWithContext(ctx context.Context) *GetPrivateChangeSubaccountNameParams {
	var ()
	return &GetPrivateChangeSubaccountNameParams{

		Context: ctx,
	}
}

// NewGetPrivateChangeSubaccountNameParamsWithHTTPClient creates a new GetPrivateChangeSubaccountNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrivateChangeSubaccountNameParamsWithHTTPClient(client *http.Client) *GetPrivateChangeSubaccountNameParams {
	var ()
	return &GetPrivateChangeSubaccountNameParams{
		HTTPClient: client,
	}
}

/*GetPrivateChangeSubaccountNameParams contains all the parameters to send to the API endpoint
for the get private change subaccount name operation typically these are written to a http.Request
*/
type GetPrivateChangeSubaccountNameParams struct {

	/*Name
	  The new user name

	*/
	Name string
	/*Sid
	  The user id for the subaccount

	*/
	Sid int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get private change subaccount name params
func (o *GetPrivateChangeSubaccountNameParams) WithTimeout(timeout time.Duration) *GetPrivateChangeSubaccountNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get private change subaccount name params
func (o *GetPrivateChangeSubaccountNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get private change subaccount name params
func (o *GetPrivateChangeSubaccountNameParams) WithContext(ctx context.Context) *GetPrivateChangeSubaccountNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get private change subaccount name params
func (o *GetPrivateChangeSubaccountNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get private change subaccount name params
func (o *GetPrivateChangeSubaccountNameParams) WithHTTPClient(client *http.Client) *GetPrivateChangeSubaccountNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get private change subaccount name params
func (o *GetPrivateChangeSubaccountNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get private change subaccount name params
func (o *GetPrivateChangeSubaccountNameParams) WithName(name string) *GetPrivateChangeSubaccountNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get private change subaccount name params
func (o *GetPrivateChangeSubaccountNameParams) SetName(name string) {
	o.Name = name
}

// WithSid adds the sid to the get private change subaccount name params
func (o *GetPrivateChangeSubaccountNameParams) WithSid(sid int64) *GetPrivateChangeSubaccountNameParams {
	o.SetSid(sid)
	return o
}

// SetSid adds the sid to the get private change subaccount name params
func (o *GetPrivateChangeSubaccountNameParams) SetSid(sid int64) {
	o.Sid = sid
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrivateChangeSubaccountNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {
		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	// query param sid
	qrSid := o.Sid
	qSid := swag.FormatInt64(qrSid)
	if qSid != "" {
		if err := r.SetQueryParam("sid", qSid); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
