// Code generated by make generate-models DO NOT EDIT.

package notifications

type BookInstrumentNameIntervalRepeated struct {
	Asks             [][]interface{} `json:"asks" mapstructure:"asks"`
	Bids             []interface{}   `json:"bids" mapstructure:"bids"`
	ChangeID         int64           `json:"change_id" mapstructure:"change_id"`
	InstrumentName   string          `json:"instrument_name" mapstructure:"instrument_name"`
	PreviousChangeID int64           `json:"previous_change_id" mapstructure:"previous_change_id"`
	Timestamp        int64           `json:"timestamp" mapstructure:"timestamp"`
}
