// Code generated by go-swagger; DO NOT EDIT.

package websocket_only

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrivateEnableCancelOnDisconnectParams creates a new GetPrivateEnableCancelOnDisconnectParams object
// with the default values initialized.
func NewGetPrivateEnableCancelOnDisconnectParams() *GetPrivateEnableCancelOnDisconnectParams {

	return &GetPrivateEnableCancelOnDisconnectParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrivateEnableCancelOnDisconnectParamsWithTimeout creates a new GetPrivateEnableCancelOnDisconnectParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrivateEnableCancelOnDisconnectParamsWithTimeout(timeout time.Duration) *GetPrivateEnableCancelOnDisconnectParams {

	return &GetPrivateEnableCancelOnDisconnectParams{

		timeout: timeout,
	}
}

// NewGetPrivateEnableCancelOnDisconnectParamsWithContext creates a new GetPrivateEnableCancelOnDisconnectParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrivateEnableCancelOnDisconnectParamsWithContext(ctx context.Context) *GetPrivateEnableCancelOnDisconnectParams {

	return &GetPrivateEnableCancelOnDisconnectParams{

		Context: ctx,
	}
}

// NewGetPrivateEnableCancelOnDisconnectParamsWithHTTPClient creates a new GetPrivateEnableCancelOnDisconnectParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrivateEnableCancelOnDisconnectParamsWithHTTPClient(client *http.Client) *GetPrivateEnableCancelOnDisconnectParams {

	return &GetPrivateEnableCancelOnDisconnectParams{
		HTTPClient: client,
	}
}

/*GetPrivateEnableCancelOnDisconnectParams contains all the parameters to send to the API endpoint
for the get private enable cancel on disconnect operation typically these are written to a http.Request
*/
type GetPrivateEnableCancelOnDisconnectParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get private enable cancel on disconnect params
func (o *GetPrivateEnableCancelOnDisconnectParams) WithTimeout(timeout time.Duration) *GetPrivateEnableCancelOnDisconnectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get private enable cancel on disconnect params
func (o *GetPrivateEnableCancelOnDisconnectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get private enable cancel on disconnect params
func (o *GetPrivateEnableCancelOnDisconnectParams) WithContext(ctx context.Context) *GetPrivateEnableCancelOnDisconnectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get private enable cancel on disconnect params
func (o *GetPrivateEnableCancelOnDisconnectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get private enable cancel on disconnect params
func (o *GetPrivateEnableCancelOnDisconnectParams) WithHTTPClient(client *http.Client) *GetPrivateEnableCancelOnDisconnectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get private enable cancel on disconnect params
func (o *GetPrivateEnableCancelOnDisconnectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrivateEnableCancelOnDisconnectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
