// Code generated by go-swagger; DO NOT EDIT.

package market_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPublicGetBookSummaryByCurrencyParams creates a new GetPublicGetBookSummaryByCurrencyParams object
// with the default values initialized.
func NewGetPublicGetBookSummaryByCurrencyParams() *GetPublicGetBookSummaryByCurrencyParams {
	var ()
	return &GetPublicGetBookSummaryByCurrencyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPublicGetBookSummaryByCurrencyParamsWithTimeout creates a new GetPublicGetBookSummaryByCurrencyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPublicGetBookSummaryByCurrencyParamsWithTimeout(timeout time.Duration) *GetPublicGetBookSummaryByCurrencyParams {
	var ()
	return &GetPublicGetBookSummaryByCurrencyParams{

		timeout: timeout,
	}
}

// NewGetPublicGetBookSummaryByCurrencyParamsWithContext creates a new GetPublicGetBookSummaryByCurrencyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPublicGetBookSummaryByCurrencyParamsWithContext(ctx context.Context) *GetPublicGetBookSummaryByCurrencyParams {
	var ()
	return &GetPublicGetBookSummaryByCurrencyParams{

		Context: ctx,
	}
}

// NewGetPublicGetBookSummaryByCurrencyParamsWithHTTPClient creates a new GetPublicGetBookSummaryByCurrencyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPublicGetBookSummaryByCurrencyParamsWithHTTPClient(client *http.Client) *GetPublicGetBookSummaryByCurrencyParams {
	var ()
	return &GetPublicGetBookSummaryByCurrencyParams{
		HTTPClient: client,
	}
}

/*GetPublicGetBookSummaryByCurrencyParams contains all the parameters to send to the API endpoint
for the get public get book summary by currency operation typically these are written to a http.Request
*/
type GetPublicGetBookSummaryByCurrencyParams struct {

	/*Currency
	  The currency symbol

	*/
	Currency string
	/*Kind
	  Instrument kind, if not provided instruments of all kinds are considered

	*/
	Kind *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get public get book summary by currency params
func (o *GetPublicGetBookSummaryByCurrencyParams) WithTimeout(timeout time.Duration) *GetPublicGetBookSummaryByCurrencyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get public get book summary by currency params
func (o *GetPublicGetBookSummaryByCurrencyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get public get book summary by currency params
func (o *GetPublicGetBookSummaryByCurrencyParams) WithContext(ctx context.Context) *GetPublicGetBookSummaryByCurrencyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get public get book summary by currency params
func (o *GetPublicGetBookSummaryByCurrencyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get public get book summary by currency params
func (o *GetPublicGetBookSummaryByCurrencyParams) WithHTTPClient(client *http.Client) *GetPublicGetBookSummaryByCurrencyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get public get book summary by currency params
func (o *GetPublicGetBookSummaryByCurrencyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCurrency adds the currency to the get public get book summary by currency params
func (o *GetPublicGetBookSummaryByCurrencyParams) WithCurrency(currency string) *GetPublicGetBookSummaryByCurrencyParams {
	o.SetCurrency(currency)
	return o
}

// SetCurrency adds the currency to the get public get book summary by currency params
func (o *GetPublicGetBookSummaryByCurrencyParams) SetCurrency(currency string) {
	o.Currency = currency
}

// WithKind adds the kind to the get public get book summary by currency params
func (o *GetPublicGetBookSummaryByCurrencyParams) WithKind(kind *string) *GetPublicGetBookSummaryByCurrencyParams {
	o.SetKind(kind)
	return o
}

// SetKind adds the kind to the get public get book summary by currency params
func (o *GetPublicGetBookSummaryByCurrencyParams) SetKind(kind *string) {
	o.Kind = kind
}

// WriteToRequest writes these params to a swagger request
func (o *GetPublicGetBookSummaryByCurrencyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param currency
	qrCurrency := o.Currency
	qCurrency := qrCurrency
	if qCurrency != "" {
		if err := r.SetQueryParam("currency", qCurrency); err != nil {
			return err
		}
	}

	if o.Kind != nil {

		// query param kind
		var qrKind string
		if o.Kind != nil {
			qrKind = *o.Kind
		}
		qKind := qrKind
		if qKind != "" {
			if err := r.SetQueryParam("kind", qKind); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
