#!/usr/bin/env bash
shopt -s nullglob

printf "// Code generated by make generate-methods DO NOT EDIT.\n\npackage deribit" > rpc_methods.go
printf "// Code generated by make generate-methods DO NOT EDIT.\n\npackage deribit" > rpc_subscriptions.go

go run cmd/gen/main.go --subscriptions >> rpc_subscriptions.go

for p in private public; do
    for f in examples/${p}/*.request.json; do
        name=$(basename "${f%.*}")
        go run cmd/gen/main.go --method=${name%.*} --namespace=${p} >> rpc_methods.go
    done
done
