#!/usr/bin/env bash
shopt -s nullglob

printf "// Code generated by make generate-methods DO NOT EDIT.\n\npackage deribit" > rpc_methods.go
printf "// Code generated by make generate-methods DO NOT EDIT.\n\npackage deribit" > rpc_subscriptions.go

go run cmd/gen/main.go --subscriptions >> rpc_subscriptions.go

for f in $(cat schema/swagger.json | jq -c '.paths | to_entries | .[] | {path: .key, type: .value.get.responses."200".schema."$ref"}'); do
    path=$(echo ${f} | jq -r '.path')
    type=$(echo ${f} | jq -r '.type')
    echo $path
done

