// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/adampointer/go-deribit/v3/models"
)

// GetPrivateWithdrawReader is a Reader for the GetPrivateWithdraw structure.
type GetPrivateWithdrawReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrivateWithdrawReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPrivateWithdrawOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrivateWithdrawOK creates a GetPrivateWithdrawOK with default headers values
func NewGetPrivateWithdrawOK() *GetPrivateWithdrawOK {
	return &GetPrivateWithdrawOK{}
}

/*GetPrivateWithdrawOK handles this case with default header values.

GetPrivateWithdrawOK get private withdraw o k
*/
type GetPrivateWithdrawOK struct {
	Payload *models.PrivateWithdrawResponse
}

func (o *GetPrivateWithdrawOK) Error() string {
	return fmt.Sprintf("[GET /private/withdraw][%d] getPrivateWithdrawOK  %+v", 200, o.Payload)
}

func (o *GetPrivateWithdrawOK) GetPayload() *models.PrivateWithdrawResponse {
	return o.Payload
}

func (o *GetPrivateWithdrawOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PrivateWithdrawResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
