// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Asks asks
// swagger:model asks
type Asks [][]float64

// Validate validates this asks
func (m Asks) Validate(formats strfmt.Registry) error {
	return nil
}
