// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// BestBidAmount It represents the requested order size of all best bids
// swagger:model best_bid_amount
type BestBidAmount float64

// Validate validates this best bid amount
func (m BestBidAmount) Validate(formats strfmt.Registry) error {
	return nil
}
