// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// CurrencyTransactionID Transaction id in proper format for currency, `null` if id is not available
// swagger:model currency_transaction_id
type CurrencyTransactionID string

// Validate validates this currency transaction id
func (m CurrencyTransactionID) Validate(formats strfmt.Registry) error {
	return nil
}
