// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Fee Fee in currency
// swagger:model fee
type Fee float64

// Validate validates this fee
func (m Fee) Validate(formats strfmt.Registry) error {
	return nil
}
