// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// OrderID Unique order identifier
// swagger:model order_id
type OrderID string

// Validate validates this order id
func (m OrderID) Validate(formats strfmt.Registry) error {
	return nil
}
