// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PrivateGetMarginsResponse private get margins response
// swagger:model private_get_margins_response
type PrivateGetMarginsResponse struct {
	BaseMessage

	// result
	// Required: true
	Result *PrivateGetMarginsResponseAO1Result `json:"result"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PrivateGetMarginsResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BaseMessage
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BaseMessage = aO0

	// AO1
	var dataAO1 struct {
		Result *PrivateGetMarginsResponseAO1Result `json:"result"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Result = dataAO1.Result

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PrivateGetMarginsResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.BaseMessage)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		Result *PrivateGetMarginsResponseAO1Result `json:"result"`
	}

	dataAO1.Result = m.Result

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this private get margins response
func (m *PrivateGetMarginsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BaseMessage
	if err := m.BaseMessage.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PrivateGetMarginsResponse) validateResult(formats strfmt.Registry) error {

	if err := validate.Required("result", "body", m.Result); err != nil {
		return err
	}

	if m.Result != nil {
		if err := m.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PrivateGetMarginsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PrivateGetMarginsResponse) UnmarshalBinary(b []byte) error {
	var res PrivateGetMarginsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PrivateGetMarginsResponseAO1Result private get margins response a o1 result
// swagger:model PrivateGetMarginsResponseAO1Result
type PrivateGetMarginsResponseAO1Result struct {

	// Margin when buying
	// Required: true
	Buy *float64 `json:"buy"`

	// max price
	// Required: true
	MaxPrice MaxPrice `json:"max_price"`

	// min price
	// Required: true
	MinPrice MinPrice `json:"min_price"`

	// Margin when selling
	// Required: true
	Sell *float64 `json:"sell"`
}

// Validate validates this private get margins response a o1 result
func (m *PrivateGetMarginsResponseAO1Result) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxPrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMinPrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSell(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PrivateGetMarginsResponseAO1Result) validateBuy(formats strfmt.Registry) error {

	if err := validate.Required("result"+"."+"buy", "body", m.Buy); err != nil {
		return err
	}

	return nil
}

func (m *PrivateGetMarginsResponseAO1Result) validateMaxPrice(formats strfmt.Registry) error {

	if err := m.MaxPrice.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("result" + "." + "max_price")
		}
		return err
	}

	return nil
}

func (m *PrivateGetMarginsResponseAO1Result) validateMinPrice(formats strfmt.Registry) error {

	if err := m.MinPrice.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("result" + "." + "min_price")
		}
		return err
	}

	return nil
}

func (m *PrivateGetMarginsResponseAO1Result) validateSell(formats strfmt.Registry) error {

	if err := validate.Required("result"+"."+"sell", "body", m.Sell); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PrivateGetMarginsResponseAO1Result) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PrivateGetMarginsResponseAO1Result) UnmarshalBinary(b []byte) error {
	var res PrivateGetMarginsResponseAO1Result
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
