// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PublicGetOptionMarkPricesResponse public get option mark prices response
// swagger:model public_get_option_mark_prices_response
type PublicGetOptionMarkPricesResponse interface{}
