// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// SettlementPrice The settlement price for the instrument. Only when `state = open`
// swagger:model settlement_price
type SettlementPrice float64

// Validate validates this settlement price
func (m SettlementPrice) Validate(formats strfmt.Registry) error {
	return nil
}
