// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TradeSeq The sequence number of the trade within instrument
// swagger:model trade_seq
type TradeSeq int64

// Validate validates this trade seq
func (m TradeSeq) Validate(formats strfmt.Registry) error {
	return nil
}
