// Code generated by go-swagger; DO NOT EDIT.

package account_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrivateGetNewAnnouncementsParams creates a new GetPrivateGetNewAnnouncementsParams object
// with the default values initialized.
func NewGetPrivateGetNewAnnouncementsParams() *GetPrivateGetNewAnnouncementsParams {

	return &GetPrivateGetNewAnnouncementsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrivateGetNewAnnouncementsParamsWithTimeout creates a new GetPrivateGetNewAnnouncementsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrivateGetNewAnnouncementsParamsWithTimeout(timeout time.Duration) *GetPrivateGetNewAnnouncementsParams {

	return &GetPrivateGetNewAnnouncementsParams{

		timeout: timeout,
	}
}

// NewGetPrivateGetNewAnnouncementsParamsWithContext creates a new GetPrivateGetNewAnnouncementsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrivateGetNewAnnouncementsParamsWithContext(ctx context.Context) *GetPrivateGetNewAnnouncementsParams {

	return &GetPrivateGetNewAnnouncementsParams{

		Context: ctx,
	}
}

// NewGetPrivateGetNewAnnouncementsParamsWithHTTPClient creates a new GetPrivateGetNewAnnouncementsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrivateGetNewAnnouncementsParamsWithHTTPClient(client *http.Client) *GetPrivateGetNewAnnouncementsParams {

	return &GetPrivateGetNewAnnouncementsParams{
		HTTPClient: client,
	}
}

/*GetPrivateGetNewAnnouncementsParams contains all the parameters to send to the API endpoint
for the get private get new announcements operation typically these are written to a http.Request
*/
type GetPrivateGetNewAnnouncementsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get private get new announcements params
func (o *GetPrivateGetNewAnnouncementsParams) WithTimeout(timeout time.Duration) *GetPrivateGetNewAnnouncementsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get private get new announcements params
func (o *GetPrivateGetNewAnnouncementsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get private get new announcements params
func (o *GetPrivateGetNewAnnouncementsParams) WithContext(ctx context.Context) *GetPrivateGetNewAnnouncementsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get private get new announcements params
func (o *GetPrivateGetNewAnnouncementsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get private get new announcements params
func (o *GetPrivateGetNewAnnouncementsParams) WithHTTPClient(client *http.Client) *GetPrivateGetNewAnnouncementsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get private get new announcements params
func (o *GetPrivateGetNewAnnouncementsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrivateGetNewAnnouncementsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
