// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrivateOrderhistoryParams creates a new GetPrivateOrderhistoryParams object
// with the default values initialized.
func NewGetPrivateOrderhistoryParams() *GetPrivateOrderhistoryParams {
	var ()
	return &GetPrivateOrderhistoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrivateOrderhistoryParamsWithTimeout creates a new GetPrivateOrderhistoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrivateOrderhistoryParamsWithTimeout(timeout time.Duration) *GetPrivateOrderhistoryParams {
	var ()
	return &GetPrivateOrderhistoryParams{

		timeout: timeout,
	}
}

// NewGetPrivateOrderhistoryParamsWithContext creates a new GetPrivateOrderhistoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrivateOrderhistoryParamsWithContext(ctx context.Context) *GetPrivateOrderhistoryParams {
	var ()
	return &GetPrivateOrderhistoryParams{

		Context: ctx,
	}
}

// NewGetPrivateOrderhistoryParamsWithHTTPClient creates a new GetPrivateOrderhistoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrivateOrderhistoryParamsWithHTTPClient(client *http.Client) *GetPrivateOrderhistoryParams {
	var ()
	return &GetPrivateOrderhistoryParams{
		HTTPClient: client,
	}
}

/*GetPrivateOrderhistoryParams contains all the parameters to send to the API endpoint
for the get private orderhistory operation typically these are written to a http.Request
*/
type GetPrivateOrderhistoryParams struct {

	/*Count
	  the number of items to be returned.

	*/
	Count *float64
	/*Instrument
	  Either the name of an instrument, "future" of "option"

	*/
	Instrument *string
	/*Offset
	  The offset for pagination

	*/
	Offset *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) WithTimeout(timeout time.Duration) *GetPrivateOrderhistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) WithContext(ctx context.Context) *GetPrivateOrderhistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) WithHTTPClient(client *http.Client) *GetPrivateOrderhistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) WithCount(count *float64) *GetPrivateOrderhistoryParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) SetCount(count *float64) {
	o.Count = count
}

// WithInstrument adds the instrument to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) WithInstrument(instrument *string) *GetPrivateOrderhistoryParams {
	o.SetInstrument(instrument)
	return o
}

// SetInstrument adds the instrument to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) SetInstrument(instrument *string) {
	o.Instrument = instrument
}

// WithOffset adds the offset to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) WithOffset(offset *float64) *GetPrivateOrderhistoryParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get private orderhistory params
func (o *GetPrivateOrderhistoryParams) SetOffset(offset *float64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrivateOrderhistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount float64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatFloat64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.Instrument != nil {

		// query param instrument
		var qrInstrument string
		if o.Instrument != nil {
			qrInstrument = *o.Instrument
		}
		qInstrument := qrInstrument
		if qInstrument != "" {
			if err := r.SetQueryParam("instrument", qInstrument); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset float64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatFloat64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
