// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/adampointer/go-deribit/models"
)

// GetPublicHelloReader is a Reader for the GetPublicHello structure.
type GetPublicHelloReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPublicHelloReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPublicHelloOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPublicHelloOK creates a GetPublicHelloOK with default headers values
func NewGetPublicHelloOK() *GetPublicHelloOK {
	return &GetPublicHelloOK{}
}

/*GetPublicHelloOK handles this case with default header values.

GetPublicHelloOK get public hello o k
*/
type GetPublicHelloOK struct {
	Payload *models.PublicTestResponse
}

func (o *GetPublicHelloOK) Error() string {
	return fmt.Sprintf("[GET /public/hello][%d] getPublicHelloOK  %+v", 200, o.Payload)
}

func (o *GetPublicHelloOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PublicTestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
