// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPublicPingParams creates a new GetPublicPingParams object
// with the default values initialized.
func NewGetPublicPingParams() *GetPublicPingParams {

	return &GetPublicPingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPublicPingParamsWithTimeout creates a new GetPublicPingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPublicPingParamsWithTimeout(timeout time.Duration) *GetPublicPingParams {

	return &GetPublicPingParams{

		timeout: timeout,
	}
}

// NewGetPublicPingParamsWithContext creates a new GetPublicPingParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPublicPingParamsWithContext(ctx context.Context) *GetPublicPingParams {

	return &GetPublicPingParams{

		Context: ctx,
	}
}

// NewGetPublicPingParamsWithHTTPClient creates a new GetPublicPingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPublicPingParamsWithHTTPClient(client *http.Client) *GetPublicPingParams {

	return &GetPublicPingParams{
		HTTPClient: client,
	}
}

/*GetPublicPingParams contains all the parameters to send to the API endpoint
for the get public ping operation typically these are written to a http.Request
*/
type GetPublicPingParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get public ping params
func (o *GetPublicPingParams) WithTimeout(timeout time.Duration) *GetPublicPingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get public ping params
func (o *GetPublicPingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get public ping params
func (o *GetPublicPingParams) WithContext(ctx context.Context) *GetPublicPingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get public ping params
func (o *GetPublicPingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get public ping params
func (o *GetPublicPingParams) WithHTTPClient(client *http.Client) *GetPublicPingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get public ping params
func (o *GetPublicPingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPublicPingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
