// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/adampointer/go-deribit/models"
)

// GetPublicSetHeartbeatReader is a Reader for the GetPublicSetHeartbeat structure.
type GetPublicSetHeartbeatReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPublicSetHeartbeatReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPublicSetHeartbeatOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPublicSetHeartbeatOK creates a GetPublicSetHeartbeatOK with default headers values
func NewGetPublicSetHeartbeatOK() *GetPublicSetHeartbeatOK {
	return &GetPublicSetHeartbeatOK{}
}

/*GetPublicSetHeartbeatOK handles this case with default header values.

foo
*/
type GetPublicSetHeartbeatOK struct {
	Payload *models.OkResponse
}

func (o *GetPublicSetHeartbeatOK) Error() string {
	return fmt.Sprintf("[GET /public/set_heartbeat][%d] getPublicSetHeartbeatOK  %+v", 200, o.Payload)
}

func (o *GetPublicSetHeartbeatOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OkResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
