// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/adampointer/go-deribit/models"
)

// GetPrivateDatatableReader is a Reader for the GetPrivateDatatable structure.
type GetPrivateDatatableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrivateDatatableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrivateDatatableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrivateDatatableOK creates a GetPrivateDatatableOK with default headers values
func NewGetPrivateDatatableOK() *GetPrivateDatatableOK {
	return &GetPrivateDatatableOK{}
}

/*GetPrivateDatatableOK handles this case with default header values.

foo
*/
type GetPrivateDatatableOK struct {
	Payload *models.OkResponse
}

func (o *GetPrivateDatatableOK) Error() string {
	return fmt.Sprintf("[GET /private/datatable][%d] getPrivateDatatableOK  %+v", 200, o.Payload)
}

func (o *GetPrivateDatatableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OkResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
