// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// BestBidPrice The current best bid price, `null` if there aren't any bids
// swagger:model best_bid_price
type BestBidPrice float64

// Validate validates this best bid price
func (m BestBidPrice) Validate(formats strfmt.Registry) error {
	return nil
}
