// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Commission Commission paid so far (in base currency)
// swagger:model commission
type Commission float64

// Validate validates this commission
func (m Commission) Validate(formats strfmt.Registry) error {
	return nil
}
