// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Label user defined label (up to 32 characters)
// swagger:model label
type Label string

// Validate validates this label
func (m Label) Validate(formats strfmt.Registry) error {
	return nil
}
