// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MarkPriceInfo mark price info
// swagger:model mark_price_info
type MarkPriceInfo struct {

	// instrument name
	InstrumentName string `json:"instrument_name,omitempty"`

	// implied volatility of mark price
	Iv float64 `json:"iv,omitempty"`

	// mark_price of instrument
	MarkPrice float64 `json:"mark_price,omitempty"`
}

// Validate validates this mark price info
func (m *MarkPriceInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarkPriceInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarkPriceInfo) UnmarshalBinary(b []byte) error {
	var res MarkPriceInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
