// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// OpenInterest The total amount of outstanding contracts in the corresponding amount units. For perpetual and futures the amount is in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH.
// swagger:model open_interest
type OpenInterest float64

// Validate validates this open interest
func (m OpenInterest) Validate(formats strfmt.Registry) error {
	return nil
}
