// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ReduceOnly `true` for reduce-only orders only
// swagger:model reduce_only
type ReduceOnly bool

// Validate validates this reduce only
func (m ReduceOnly) Validate(formats strfmt.Registry) error {
	return nil
}
