// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TickDirection Direction of the "tick" (`0` = Plus Tick, `1` = Zero-Plus Tick, `2` = Minus Tick, `3` = Zero-Minus Tick).
// swagger:model tick_direction
type TickDirection int64

// for schema
var tickDirectionEnum []interface{}

func init() {
	var res []TickDirection
	if err := json.Unmarshal([]byte(`[0,1,2,3]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tickDirectionEnum = append(tickDirectionEnum, v)
	}
}

func (m TickDirection) validateTickDirectionEnum(path, location string, value TickDirection) error {
	if err := validate.Enum(path, location, value, tickDirectionEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tick direction
func (m TickDirection) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTickDirectionEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
