// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TransferID Id of transfer
// swagger:model transfer_id
type TransferID int64

// Validate validates this transfer id
func (m TransferID) Validate(formats strfmt.Registry) error {
	return nil
}
